package game;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws Exception {
        Server server = new Server(1515);
        server.start();

    }
}